# Tkabber-pack Makefile 
# based on WinTclTk Makefile
# Copyright (c) 2006-2008 Martin Matuska
# Copyright (c) 2014 Vitaly Takmazov
#
CURDIR=	$(shell pwd)
SRCDIR=	$(CURDIR)
MDIR?=	defs

include $(MDIR)/defs.mak

BUILDDIR?=	$(CURDIR)/build
PREFIX?=	$(CURDIR)/../tcl
include $(MDIR)/shared.mak

COMMONBUILD?=	$(BUILDDIR)
include $(MDIR)/common.mak
