name: CI

on: [push]

jobs:
  msys:
    runs-on: windows-latest
    steps:
      - name: Prepare
        uses: actions/checkout@v1
      - name: Download MSYS
        shell: bash
        run: curl -o mingw-get.tar.xz -L -s https://osdn.mirror.constant.com//mingw/68260/mingw-get-0.6.3-mingw32-pre-20170905-1-bin.tar.xz
      - name: Install MSYS
        shell: bash
        run: |          
          mkdir MinGW
          cd MinGW          
          tar -xf ../mingw-get.tar.xz
          cd bin
          ./mingw-get install msys-make mingw32-gcc mingw32-autoconf
      - name: Build
        shell: bash
        run: |
          export PATH=$(PWD)/MinGW/msys/1.0/bin:$PATH
          bash configure
          make install
  i686-w64-mingw32-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install mingw-w64 mingw-w64-i686-dev tclsh tcllib
    - name: Build
      run: |
        ./configure --host=i686-w64-mingw32
        make install
        
  x86_64-w64-mingw32-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install mingw-w64 tclsh tcllib
    - name: Build
      run: |
        ./configure --host=x86_64-w64-mingw32
        make install
        
  macos:
    runs-on: macos-latest
    steps:
    - name: Prepare
      uses: actions/checkout@v1      
    - name: Install dependencies
      run: |
        brew install autoconf automake
    - name: Build
      shell: bash
      run: |
        ./configure
        make install
