name: CI

on: [push]

jobs:
  i686-w64-mingw32-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install mingw-w64 mingw-w64-i686-dev tclsh tcllib
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc
        make
        
  x86_64-w64-mingw32-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install mingw-w64 tclsh tcllib
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc
        make
        
  macos:
    runs-on: macos-latest
    steps:
    - name: Prepare
      uses: actions/checkout@v1      
    - name: Install dependencies
      run: |
        brew install autoconf automake
    - name: Build
      shell: bash
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=dist
        make
